name: Build LaTeX document (upload artifact)

on:
  push:
    branches:
      - master
    tags:
      - "v*"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: src/
          latexmk_shell_escape: true
          extra_system_packages: "py-pygments"
      - name: Rename PDF file
        id: rename-pdf-file
        run: mv src/main.pdf src/dispensa-fisica.pdf
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-dispensa
          path: src/dispensa-fisica.pdf
        if: ${{ success() }}
      - name: Send dispensa to Telegram Group
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: New release available!
          document: src/dispensa-fisica.pdf
        if: ${{ success() }}